// Path: CraftingInterpreters.CSLox.Core/LoxExpression.cs
// This file was generated by the tool at CraftingInterpreters.CSLox.Tools
// Do not edit this file directly.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CraftingInterpreters.CSLox.Core;

public abstract class Expression
{
	static class Binary : Expression
		Binary(Expression left, Token operator, Expression right)
		{
			this.Left = left;
			this.Operator = operator;
			this.Right = right;
		}

		public Expression Left { get; set; }
		public Token Operator { get; set; }
		public Expression Right { get; set; }

	static class Grouping : Expression
		Grouping(Expression expression)
		{
			this.Expression = expression;
		}

		public Expression Expression { get; set; }

	static class Literal : Expression
		Literal(object value)
		{
			this.Value = value;
		}

		public object Value { get; set; }

	static class Unary : Expression
		Unary(Token operator, Expression right)
		{
			this.Operator = operator;
			this.Right = right;
		}

		public Token Operator { get; set; }
		public Expression Right { get; set; }

}

