// Path: CraftingInterpreters.CSLox.Core/LoxExpression.cs
// This file was generated by the tool at CraftingInterpreters.CSLox.Tools
// Do not edit this file directly.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CraftingInterpreters.CSLox.Core;

public abstract class LoxExpression
{
	public class Binary : LoxExpression
	{
		public Binary(LoxExpression left, Token @operator, LoxExpression right)
		{
			this.Left = left;
			this.Operator = @operator;
			this.Right = right;
		}

		public LoxExpression Left { get; set; }
		public Token Operator { get; set; }
		public LoxExpression Right { get; set; }

	}

	public class Grouping : LoxExpression
	{
		public Grouping(LoxExpression expression)
		{
			this.Expression = expression;
		}

		public LoxExpression Expression { get; set; }

	}

	public class Literal : LoxExpression
	{
		public Literal(object value)
		{
			this.Value = value;
		}

		public object Value { get; set; }

	}

	public class Unary : LoxExpression
	{
		public Unary(Token @operator, LoxExpression right)
		{
			this.Operator = @operator;
			this.Right = right;
		}

		public Token Operator { get; set; }
		public LoxExpression Right { get; set; }

	}

}

