// Path: CraftingInterpreters.CSLox.Core/LoxExpression.cs
// This file was generated by the tool at CraftingInterpreters.CSLox.Tools
// Do not edit this file directly.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CraftingInterpreters.CSLox.Core;

public abstract class LoxStatement
{
	public abstract T Accept<T>(ILoxStatementVisitor<T> visitor);
}

public interface ILoxStatementVisitor<T>
{
	T VisitBlockLoxStatement(BlockLoxStatement loxExpression);
	T VisitExpressionLoxStatement(ExpressionLoxStatement loxExpression);
	T VisitIfLoxStatement(IfLoxStatement loxExpression);
	T VisitPrintLoxStatement(PrintLoxStatement loxExpression);
	T VisitVariableLoxStatement(VariableLoxStatement loxExpression);
}

public class BlockLoxStatement : LoxStatement
{
	public BlockLoxStatement(List<LoxStatement> statements)
	{
		this.Statements = statements;
	}

	public override T Accept<T>(ILoxStatementVisitor<T> visitor)
	{
		return visitor.VisitBlockLoxStatement(this);
	}

	public List<LoxStatement> Statements { get; set; }

}

public class ExpressionLoxStatement : LoxStatement
{
	public ExpressionLoxStatement(LoxExpression expression)
	{
		this.Expression = expression;
	}

	public override T Accept<T>(ILoxStatementVisitor<T> visitor)
	{
		return visitor.VisitExpressionLoxStatement(this);
	}

	public LoxExpression Expression { get; set; }

}

public class IfLoxStatement : LoxStatement
{
	public IfLoxStatement(LoxExpression condition, LoxStatement thenBranch, LoxStatement elseBranch)
	{
		this.Condition = condition;
		this.ThenBranch = thenBranch;
		this.ElseBranch = elseBranch;
	}

	public override T Accept<T>(ILoxStatementVisitor<T> visitor)
	{
		return visitor.VisitIfLoxStatement(this);
	}

	public LoxExpression Condition { get; set; }
	public LoxStatement ThenBranch { get; set; }
	public LoxStatement ElseBranch { get; set; }

}

public class PrintLoxStatement : LoxStatement
{
	public PrintLoxStatement(LoxExpression expression)
	{
		this.Expression = expression;
	}

	public override T Accept<T>(ILoxStatementVisitor<T> visitor)
	{
		return visitor.VisitPrintLoxStatement(this);
	}

	public LoxExpression Expression { get; set; }

}

public class VariableLoxStatement : LoxStatement
{
	public VariableLoxStatement(Token name, LoxExpression initializer)
	{
		this.Name = name;
		this.Initializer = initializer;
	}

	public override T Accept<T>(ILoxStatementVisitor<T> visitor)
	{
		return visitor.VisitVariableLoxStatement(this);
	}

	public Token Name { get; set; }
	public LoxExpression Initializer { get; set; }

}


