// See https://aka.ms/new-console-template for more information

using System.Xml.Linq;

Console.WriteLine("Hello, World!");
Console.WriteLine("Enter the ouput file name: ");
var outputDirectory = Console.ReadLine();

DefineAst(outputDirectory, "LoxExpression", new()
{
	"Binary   : LoxExpression left, Token @operator, LoxExpression right",
	"Grouping : LoxExpression expression",
	"Literal  : object value",
	"Unary    : Token @operator, LoxExpression right"
});

Console.WriteLine($"Done - File has been generated at {outputDirectory}.");

static void DefineAst(string outputDir, string baseName, List<string> types)
{
	var path = $"{outputDir}/{baseName}.cs";
	using var writer = new StreamWriter(path);
	writer.WriteLine("// Path: CraftingInterpreters.CSLox.Core/LoxExpression.cs");
	writer.WriteLine("// This file was generated by the tool at CraftingInterpreters.CSLox.Tools");
	writer.WriteLine("// Do not edit this file directly.");
	writer.WriteLine();
	writer.WriteLine("using System;");
	writer.WriteLine("using System.Collections.Generic;");
	writer.WriteLine("using System.Linq;");
	writer.WriteLine("using System.Text;");
	writer.WriteLine("using System.Threading.Tasks;");
	writer.WriteLine();
	writer.WriteLine("namespace CraftingInterpreters.CSLox.Core;");
	writer.WriteLine();
	writer.WriteLine($"public abstract class {baseName}");
	writer.WriteLine("{");

	foreach (var type in types)
	{
		var className = type.Split(":")[0].Trim();
		var fields = type.Split(":")[1].Trim();
		DefineType(writer, baseName, className, fields);
	}

	writer.WriteLine("}");
	writer.WriteLine();

	writer.Dispose();

}

static void DefineType(StreamWriter writer, string baseName, string className, string fields)
{
	writer.WriteLine($"\tpublic class {className} : {baseName}");
	writer.WriteLine("\t{");
	// Constructor
	writer.WriteLine($"\t\tpublic {className}({fields})");
	writer.WriteLine("\t\t{");

	// Define the fields
	var fieldList = fields.Split(", ");
	foreach (var field in fieldList)
	{
		var name = field.Split(" ")[1];
		var propertyName = GetPropertyName(name);
		writer.WriteLine($"\t\t\tthis.{propertyName} = {name};");
	}

	writer.WriteLine("\t\t}");
	writer.WriteLine();

	// Define the properties
	foreach (var field in fieldList)
	{
		var type = field.Split(" ")[0];
		var name = field.Split(" ")[1];
		name = GetPropertyName(name);
		writer.WriteLine($"\t\tpublic {type} {name} {{ get; set; }}");
	}

	writer.WriteLine();
	writer.WriteLine("\t}");
	writer.WriteLine();
}

static string GetPropertyName(string field)
{
	if (field.StartsWith("@"))
		field = field.Substring(1);
	return field.Substring(0, 1).ToUpper() + field.Substring(1);
}